# Generated by Django 3.2.16 on 2022-11-22 18:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='testpicture',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Other'),
        ),
    ]
