# Generated by Django 3.2.16 on 2022-11-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_testpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='test',
        ),
    ]
