# Generated by Django 3.2.16 on 2022-11-23 17:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221122_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
