# Generated by Django 3.2.16 on 2022-11-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('salads', 'SALADS'), ('soups', 'SOUPS'), ('dough', 'DOUGH'), ('pasta', 'PASTA'), ('rice', 'RICE'), ('meats', 'MEATS'), ('fish', 'FISH'), ('spreads', 'SPREADS'), ('sweets', 'SWEETS')], default='Add your category here', max_length=100),
        ),
    ]
